"""empty message

Revision ID: 156a5562fc1
Revises: 41983a725bfb
Create Date: 2014-03-21 11:28:18.735626

"""

# revision identifiers, used by Alembic.
revision = '156a5562fc1'
down_revision = '41983a725bfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('description', sa.UnicodeText(), nullable=True))
    op.drop_column('release', 'long_description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('long_description', sa.TEXT(), nullable=True))
    op.drop_column('release', 'description')
    ### end Alembic commands ###
