"""empty message

Revision ID: 18a811b4a283
Revises: 56b9f03f7d56
Create Date: 2014-03-18 09:51:06.562235

"""

# revision identifiers, used by Alembic.
revision = '18a811b4a283'
down_revision = '56b9f03f7d56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    op.drop_column('user', 'created')
    op.drop_column('role', 'updated')
    op.drop_column('role', 'created')
    ### end Alembic commands ###
