"""empty message

Revision ID: 213e4921aace
Revises: 59ce4b31562b
Create Date: 2014-03-21 11:37:40.460707

"""

# revision identifiers, used by Alembic.
revision = '213e4921aace'
down_revision = '59ce4b31562b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release', 'version',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release', 'version',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    ### end Alembic commands ###
