"""empty message

Revision ID: 2b1fdf95960d
Revises: 3b2364e9c33c
Create Date: 2014-03-25 14:57:46.888713

"""

# revision identifiers, used by Alembic.
revision = '2b1fdf95960d'
down_revision = '3b2364e9c33c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('package_id', sa.Integer(), nullable=False))
    op.add_column('release', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('release', 'user')
    op.drop_column('release', 'package')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('package', sa.INTEGER(), nullable=False))
    op.add_column('release', sa.Column('user', sa.INTEGER(), nullable=False))
    op.drop_column('release', 'user_id')
    op.drop_column('release', 'package_id')
    ### end Alembic commands ###
