"""empty message

Revision ID: 39a1913db39d
Revises: 213e4921aace
Create Date: 2014-03-21 11:39:23.077176

"""

# revision identifiers, used by Alembic.
revision = '39a1913db39d'
down_revision = '213e4921aace'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release', 'package',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('release', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('release', 'package',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
