"""empty message

Revision ID: 3b2364e9c33c
Revises: 39a1913db39d
Create Date: 2014-03-21 13:43:38.122603

"""

# revision identifiers, used by Alembic.
revision = '3b2364e9c33c'
down_revision = '39a1913db39d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'classifier', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classifier')
    ### end Alembic commands ###
