"""empty message

Revision ID: 41983a725bfb
Revises: 4b0df8cffd90
Create Date: 2014-03-21 11:22:48.146435

"""

# revision identifiers, used by Alembic.
revision = '41983a725bfb'
down_revision = '4b0df8cffd90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('download_url', sa.Unicode(length=512), nullable=True))
    op.add_column('release', sa.Column('home_page', sa.Unicode(length=512), nullable=True))
    op.add_column('release', sa.Column('license', sa.UnicodeText(), nullable=True))
    op.add_column('release', sa.Column('metadata_version', sa.Unicode(length=512), nullable=True))
    op.add_column('release', sa.Column('summary', sa.UnicodeText(), nullable=True))
    op.add_column('release', sa.Column('version', sa.Unicode(length=512), nullable=True))
    op.drop_column('release', 'url')
    op.drop_column('release', 'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('release', sa.Column('url', sa.TEXT(), nullable=True))
    op.drop_column('release', 'version')
    op.drop_column('release', 'summary')
    op.drop_column('release', 'metadata_version')
    op.drop_column('release', 'license')
    op.drop_column('release', 'home_page')
    op.drop_column('release', 'download_url')
    ### end Alembic commands ###
