"""empty message

Revision ID: 4b0df8cffd90
Revises: 3c2998a5f614
Create Date: 2014-03-21 08:31:43.703757

"""

# revision identifiers, used by Alembic.
revision = '4b0df8cffd90'
down_revision = '3c2998a5f614'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('mirrored', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'package', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'package')
    op.drop_column('package', 'mirrored')
    ### end Alembic commands ###
