"""empty message

Revision ID: 4ca4d48829c2
Revises: 18a811b4a283
Create Date: 2014-03-18 18:49:16.617967

"""

# revision identifiers, used by Alembic.
revision = '4ca4d48829c2'
down_revision = '18a811b4a283'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Unicode(length=128), nullable=True),
    sa.Column('author_email', sa.Unicode(length=256), nullable=True),
    sa.Column('url', sa.UnicodeText(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('long_description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('filetype', sa.Unicode(length=32), nullable=True),
    sa.Column('filename', sa.Unicode(length=32), nullable=True),
    sa.Column('storage', sa.Unicode(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifier',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release_classifiers',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('classifier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classifier_id'], ['classifier.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('release_id', 'classifier_id')
    )
    op.create_table('package_owners',
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('package_id', 'user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_owners')
    op.drop_table('release_classifiers')
    op.drop_table('package')
    op.drop_table('classifier')
    op.drop_table('file')
    op.drop_table('release')
    ### end Alembic commands ###
