"""empty message

Revision ID: 59ce4b31562b
Revises: 156a5562fc1
Create Date: 2014-03-21 11:37:08.634980

"""

# revision identifiers, used by Alembic.
revision = '59ce4b31562b'
down_revision = '156a5562fc1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
