"""empty message

Revision ID: 9b84ecb6801
Revises: 2b1fdf95960d
Create Date: 2014-03-25 15:12:14.458236

"""

# revision identifiers, used by Alembic.
revision = '9b84ecb6801'
down_revision = '2b1fdf95960d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('release_id', sa.Integer(), nullable=True))
    op.drop_column('file', 'release')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('release', sa.INTEGER(), nullable=True))
    op.drop_column('file', 'release_id')
    ### end Alembic commands ###
